//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingCore {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class MessagingCoreSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MessagingCoreSettings defaultInstance = ((MessagingCoreSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MessagingCoreSettings())));
        
        public static MessagingCoreSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5557")]
        public string CoreSocket {
            get {
                return ((string)(this["CoreSocket"]));
            }
            set {
                this["CoreSocket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5558")]
        public string CommandSocket {
            get {
                return ((string)(this["CommandSocket"]));
            }
            set {
                this["CommandSocket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00.0640000")]
        public global::System.TimeSpan CoreSocketReceivePollRate {
            get {
                return ((global::System.TimeSpan)(this["CoreSocketReceivePollRate"]));
            }
            set {
                this["CoreSocketReceivePollRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00.0640000")]
        public global::System.TimeSpan CommandSocketReceivePollRate {
            get {
                return ((global::System.TimeSpan)(this["CommandSocketReceivePollRate"]));
            }
            set {
                this["CommandSocketReceivePollRate"] = value;
            }
        }
    }
}
